version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: moonyetis-postgres
    environment:
      POSTGRES_DB: moonyetis_dev
      POSTGRES_USER: moonyetis
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moonyetis -d moonyetis_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: moonyetis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: moonyetis-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moonyetis.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
